### ISSUE TITLE
[TODO] Discord

### ISSUE THREAD

**Issue by chrisduerr** [chrisduerr/userstyles#1]
This issue is for keeping track of problems with the Discord theme.

- [x] Search Options popup for message search
- [x] Invite Popup
- [x] Message Option popout (three dots next to message)
- [x] User Profile Modal connections (view profile)
- [x] Settings Switch (needs to get round corners again)
- [x] Changelog scrollbar (at the bottom scrollbar goes beyond modal)
- [x] Notification Settings
- [x] Privacy Settings (text color too dark)
- [x] Channel hover buggy (wrong color for fraction of a second)
- [x] Help Modal (just disable that crap)
- [x] PM User List name color (names are darker than they should be)
- [x] Replace `border-radius` block with `*` and explicitly add required borders
- [x] Date separator background in chat should be a grey, not a red line
- [x] Fix new message in other guild indicator
- [x] User Profile Modal status (remove hard edges like everywhere else)
- [x] Typing user status not a rectangle but an oval (border-radius)
- [x] Replace voice `>` expandable icon with fontawesome
- [x] Fix embedded discord invites
- [x] Fix upload mention profile status border
- [x] Mention status border
- [x] Fix Members list role dropdown
- [x] Fix status border at bottom of channel list
- [x] Fix issues with chromium/app (scrollbar has problems on app)
- [x] Fix FontAwesome using the discord app
- [x] PM field of profile popup has black fg color
- [x] Fix status border in small and big profile popup
- [x] Add hover tooltips again (at least for guilds)
- [x] Fix emoji-picker scrollbar placeholder background
- [x] Fix PM/Friend list status border color
- [x] Fix ban reason text input background color
- [x] Improve settings menu themeing (Mainly blocks aren't #262626 anymore)
- [x] Search results box-shadow not hidden anymore
- [x] Remove line under voice controls/profile
- [x] Fix status border of voice controls/profile
- [x] Remove light shadow at the top of pings notifications for channels
- [x] Fix delete message popup (migrated to new CSS) 
- [x] Fix mention and emoji completion popup
- [x] Theme search popup 
- [x] Fix upload mentions
- [x] Add border to profile popup
- [x] When clicking on a user in the user list and moving the mouse away, the bg is blue

**Comment by chrisduerr** [comment]
This kinda is a mess. There should be a better way of keeping track of this. Maybe keep a ton of small issues that have labels for Discord/Reddit/... and then just work like that. I'll close this for now and move everything open to the new structure.
