### ISSUE TITLE
[TODO] Twitter

### ISSUE THREAD

**Issue by chrisduerr** [chrisduerr/userstyles#2]
This issue is for keeping track of problems with the Twitter theme.

- [ ] Remove option to have user-defined colors on other profiles
- [ ] Top news after searching hashtag has white bg color
- [ ] Related articles after searching hashtag has unreadable fg color

**Comment by chrisduerr** [comment]
I don't use twitter anymore and a lot of it has been broken.
It might be good to just discontinue it and drop it from this repo.

**Comment by chrisduerr** [comment]
WONTFIX
